POST http://localhost:4000/update_updateOne/
content-type: application/json

{
    "searchData":{
        "name": "some_name"
    },
    "updateData":{
        "name": "updated_name",
        "age": "updated_age"
    }
}